"""empty message

Revision ID: 155a9ef707e3
Revises: 
Create Date: 2018-05-10 13:09:53.193555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155a9ef707e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('lang', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers')
    # ### end Alembic commands ###
